### ISSUE TITLE
Implement DFT adjoint operator

### ISSUE THREAD

**Issue by landmanbester** [ska-sa/codex-africanus#10]
We currently only have the forward version of the DFT i.e. the image to vis mapping. Need to implement the adjoint to use this for deconvolution. It will be slow as hell but would be nice to have this available as a benchmark for our gridders

**Comment by sjperkins** [comment]
@landmanbester I now remember why I was being so sticky about `source` between `row` and `chan`.

Recalling our conversation this afternoon, my convention for RIME dimension ordering is `(src,time,{bl,ant},chan,corr)` and all input/output RIME arrays adhere to this ordering. The thing about `(row,src,chan)` is that `time` and `{bl,ant}` are implictly bound up with `row` (Measurement Set). So this can cause problems in that it's possible that, in order to broadcast intermediate results, a transpose/rollaxis would need to be performed get the broadcasting right.

**Comment by landmanbester** [comment]
Sensible enough. I have created a new subdirectory for the DFT. There is a slight duplication of code there since I implement a im_to_vis_kernel that essentially does the same as phase_delay but with the axis order as would be expected for a linear map from image to visibility data. There is also a vis_to_im_kernel that implements the adjoint. The reason for having the two separated is that, for the latter, we only need the direct cosine transform. While we are on the subject of implementing the DFT.H, it looks like numba doesn't support masked arrays. There has been a feature request for this since 2016 https://github.com/numba/numba/issues/1834. We need this asap for flagged data. @sjperkins any alternative ideas on this?

**Comment by landmanbester** [comment]
@sjperkins can you have a look at what I've done [here](https://github.com/landmanbester/codex-africanus/tree/adjoint_dft/africanus/dft) please? I changed the kernel computations into (functional) operators but I haven't tested them yet (although you might be happy that I haven't added any classes ;-)). Mainly I need your eyes on the dask bit. Not sure if I did that right. Also we need to think about the chunking strategies because I'm not convinced that the most efficient chunking for the adjoint is the same as for its forward operator. I will get to the tests tomorrow or Tuesday I hope

**Comment by sjperkins** [comment]
Please create a PR so that I can review?

**Comment by landmanbester** [comment]
Hmmm, if all else fails read the docs ;-) @sjperkins I have some bugs to fix before I can ask you to review, will try get this done by tomorrow

**Comment by sjperkins** [comment]
It's fine. I think just open the PR anyway, it shows the diff between the branch and master so I can get a sense of what's going on and provide suggestions

**Comment by sjperkins** [comment]
Implemented in #19
