### ISSUE TITLE
Move apply_gains to calibration section

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/codex-africanus#109]
- apply_gains currently lives in africanus.rime
- should be moved to africanus.calibration with one of  @landmanbester's PRs

**Comment by landmanbester** [comment]
Alright, I'll put this and the residual function in africanus.calibration.utils

**Comment by landmanbester** [comment]
As discussed this should not really be called apply_gains but rather apply_inverse_gains or correct_vis. I opted for the latter in https://github.com/ska-sa/codex-africanus/pull/113 but I forgot to remove the apply_gains function in the rime api. I'll remove it after your review @sjperkins

**Comment by sjperkins** [comment]
Resolved in #113 and #118
