### ISSUE TITLE
Where should the source/direction axis go

### ISSUE THREAD

**Issue by landmanbester** [ska-sa/codex-africanus#111]
In my calibration scripts I have ordered the gains according to [time, antenna, chan, direction, corr, corr]. I found this the most convenient for looping over a row based data structure because the loops can be structured according to

```python
for t in range(n_tim):
    for row in range(time_indices[t], time_indices[t] + counts[t]):
        p = int(antenna1[row])
        q = int(antenna2[row])
        for nu in range(n_chan):
            for dir in range(n_dir):
                array[row, chan, dir] = ...
```

which always has the most rapidly changing index at the end. However, the shape of the jones terms in the RIME api is [source, time, antenna, chan, corr, corr] which is not compatible with the structure I am currently using. Is there a good reason for sticking to this convention?

**Comment by o-smirnov** [comment]
Hehe, and check out this discussion too: https://github.com/ratt-ru/CubiCal/issues/277

**Comment by sjperkins** [comment]
I've generally always structured the RIME as `(source, row, chan, corrs)` as it was just easier to structure a reduction over source like this on a GPU.

**Comment by landmanbester** [comment]
I've decided to keep it as `(row, chan, source, corrs, corrs)` in the calibration scripts for now but keeping this one open until in case a good reason to change it presents itself
