### ISSUE TITLE
Description of DIE/DDE arrays passed to predict_vis() needs clarity

### ISSUE THREAD

**Issue by saiyanprince** [ska-sa/codex-africanus#131]
The description in the documentation for the keyword args **{die/dde}1_jones** and **{die/dde}2_jones** that are passed to **predict_vis()** needs a bit more clarity. The user can pass the same **G_ps** array as inputs to both the keywords, and the Hermitian transpose will be performed inside codex-africanus.

**Comment by sjperkins** [comment]
Closed by #135
