### ISSUE TITLE
SPI fitting example

### ISSUE THREAD

**Issue by landmanbester** [ska-sa/codex-africanus#132]
@KshitijT see the script in my spi_map_example branch [here](https://github.com/landmanbester/codex-africanus/tree/spi_map_example/africanus/model/spi/examples). Seems to work for me but let me know if you get stuck. I've tried to document the parset options and written a brief explanation in the README.rst for the example. Will polish and submit a PR into master once we've verified that it works. At the moment you have to set the weights by hand but will see if we can start appending the sum of the weights to the fits headers in DDF

**Comment by KshitijT** [comment]
Awesome, I'll try it out and get back to you on this, it would be great if we have this tool. Silly question - this won't work for wsclean images, right?

**Comment by landmanbester** [comment]
It should if you concatenate them into a cube and make sure that the beam
parameters are in the correct format. We can add an option to take a list
of images but i won't get to that until next week. I think there is also
something wrong with the spi error map which is why i am not writing it out
at this stage. Unfortunately I'll only be able to look at that when i get
back mid August
