### ISSUE TITLE
simple_spi_fitter ain't so simple anymore

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/codex-africanus#176]
As discussed, and driven by my scattershot demands, this is turning into the equivalent of a Swiss army knife designed by a Frenchman, so maybe step back and rethink?

I'll list the use cases required here:

## Make power beam pattern

This is such a ubiquitous operation, this should be a standalone script. Arguments:

* ``image``, cube or MFS image, this is used as a donor for the FITS header, and sets up the L/M/FREQ grid (and STOKES, when we get to polarization eventually)

* ``--ms MS --field FIELD``, as per current script, used to get range of PA angles.

* ``--sparsify-time N``, as per current script, takes every Nth timeslot

* ``-o OUTPUT_FILENAME``, output file (should be ``IMAGE.pb.fits`` by default)

* ``--beam-model FILENAME``, base filename of beam model

For simplicity, you could even decree that this functionality only lives in the standalone script (i.e. other scripts would just read a PB cube produced by this script, and not try to make their own.)

## Convolve and/or correct single image 

Take input image (or cube), and convolve it to a specified resolution and/or apply a primary beam correction (either, or both).

* ``image``, image to work with

* ``--psf MAJ MIN PA``, desired PSF parameters (prefer to use PSF over "beam" whatever Steve Gull says, because otherwise there's too many "beams" in this pot).

* ``--circ-psf MAJ``, alternative to ``--psf``, use circular PSF of the given size (called ``--circularize_beam`` now, but I think this is better).

* ``-o OUTPUT_FILENAME``, output file

Read image, read its BMAJ/BMIN/BPA, work out what additional convolution to apply to make the resolution match the specified MAJ/MIN/PA, apply the convolution. Write the new PSF size to the FITS header. If the image has no BMAJ/BMIN/BPA, assume it is a model image and just apply a convolution by specified PSF directly.

* ``--pb PBIMAGE``, if specified, apply a power beam correction from the given beam file (which must match the image size).

* ``--pb-min 0.05`` set output to 0 where power beam drops below this value.

## Spectral index fitter

* ``model [residual]`` model & residual cubes

* ``--psf`` or ``--circ-psf`` optional. If specified, convolves to specified resolution (otherwise use resolution of lowest channel?)

* ``--pb PBIMAGE.fits`` optional. If specified, applies power beam correction using the specified beam cube (and apply ``--pb-min`` as specified), and also applies it to the I0 map.

Other options as per current script. Except I don't like the use of ``--output`` to specify the set of output images (it's more conventionally used to specify an output filename). How about

* ``--products`` which images to write (currently known as ``--output``)

* ``-o/--output`` base output filename (default should be to take ``model`` and strip the .fits extension)

**Comment by landmanbester** [comment]
Ok. Sounds doable enough. Probably time to move this off into a separate repo

**Comment by landmanbester** [comment]
Alright @o-smirnov I have split these into the respective sub-routines. Have a look at the power_beam_maker and image_convolver scripts in the same directory as simple_spi_fitter in my split_spi_funcs branch and let me know ifyou manage to break them. Usage is largely as before. Run with -h for input options.

Note I still need to have a look at what is going wrong with the uncertainties

**Comment by landmanbester** [comment]
See https://github.com/ratt-ru/pfb-clean/issues/7
