### ISSUE TITLE
Chunking causes discrepancy between MeqTrees and Codex

### ISSUE THREAD

**Issue by JSKenyon** [ska-sa/codex-africanus#193]
* Codex Africanus version: master
* Python version: 3.6.9
* Operating System: Pop!_OS 18.04 LTS

### Description

While attempting to compare the MeqTrees and Codex predicts, I encountered a weird discrepancy which seems to be caused by chunking. Using a single massive chunk produces agreement between the two approaches. 

### What I Did

Ran the Codex predict example using a local MS and lsm. Ran MeqTrees with identical arguments. Resulting visibilities disagreed. Setting `--row-chunks` incredibly high removes the disagreement.

**Comment by JSKenyon** [comment]
I should emphasize that this behaviour only seems to cause problems when using feed rotation/beams/both. The errors introduced also seem to vary per run. This makes me suspect a race condition or an aliased array. I have altered the predict so that I can apply feed rotation in isolation. This still exposes the discrepancy. I will attempt to dig a little further today.

**Comment by JSKenyon** [comment]
I can now confirm that the discrepancy goes away when using `scheduler="single-threaded"`. This almost guarantees a race/alias problem.

**Comment by sjperkins** [comment]
@JSKenyon Thanks for tracking this down further. Now I'm starting to suspect the thread safety of the measures server. @bennahugo @o-smirnov do you have any insight on this, especially in the context of the following code?

https://github.com/ska-sa/codex-africanus/blob/40502a51cd1bb49346b71d86c2426742fa0fecc1/africanus/rime/parangles_casa.py#L8-L53

**Comment by sjperkins** [comment]
Eye-balling it a bit further, that code is almost certainly not thread-safe.

**Comment by sjperkins** [comment]
@JSKenyon Could you try out #195 and see if it resolves this issue?

**Comment by JSKenyon** [comment]
@sjperkins will do.

**Comment by JSKenyon** [comment]
@sjperkins I can confirm that #195 seems to fix the problem for the feed rotation. Will check the beam now.

**Comment by JSKenyon** [comment]
@sjperkins This also works for the feed rotation + beam case. #194 remains an issue but at the very least I can now get `10e-7` agreement between MeqTrees as Codex.
