### ISSUE TITLE
Upgrade to latest version of ducc

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/codex-africanus#221]
* Codex Africanus version: 0.2.6
* Python version: 3.6
* Operating System: Ubuntu 18.04

ducc 0.6.0 contains memory and performance improvements

https://github.com/ska-sa/codex-africanus/pull/204#issuecomment-693509369

**Comment by mreineck** [comment]
Unless I'm missing something, you won't have to do anything, since you always download the latest `ducc0` version from PyPI, correct?

**Comment by sjperkins** [comment]
That's generally true and while I wouldn't anticipate problems with ducc, Python dependency resolution can be quite complex. Modern Python packaging systems often specify version lock files to restrict packages to specific versions: https://stackoverflow.com/a/49867443.

This issue is more an attempt to follow best practices.

**Comment by mreineck** [comment]
I see, thanks for the explanation!
