### ISSUE TITLE
Upgrade to ducc0 0.7?

### ISSUE THREAD

**Issue by mreineck** [ska-sa/codex-africanus#232]
I just released an updated `ducc0` version with the following changes to the gridder component:

  - performance (especially scaling) improvements
  - oversampling factors up to 2.5 supported
  - new, more flexible interface in submodule `wgridder.experimental`
    (subject to further changes!)

Especially the last point might be of interest to you, because it adds the new flags `divide_by_n` and `flip_v`, which may save you some juggling with the input and output data. Currently, the gridder always divides by `n` and does not flip the `v` coordinate, and I know that at least `wsclean` needs the exact opposite of that; things are probably similar for `codex-africanus`.

**Comment by sjperkins** [comment]
Thanks @mreineck. @landmanbester would you be in interested in taking this further?

**Comment by landmanbester** [comment]
Yep, thanks @mreineck. I have to add the DI gain terms anyway so I'll bump the version then. I also just gained access to a shiny new AMD EPYC 7702P box so I am keen to test the gridder out on it

**Comment by landmanbester** [comment]
On second thought, it doesn't really make sense to put the DI gains inside the wgridder wrappers because they need to be applied per correlation. I have created https://github.com/ska-sa/codex-africanus/pull/233 to upgrade to ducc0 v0.7. Can we make a release once that has gone in please @sjperkins?

**Comment by sjperkins** [comment]
I've pushed the 0.2.9 up to master. If the CI passes, it'll be available on PyPI soon

**Comment by sjperkins** [comment]
0.2.9 is released. Thanks @mreineck and @landmanbester
