### ISSUE TITLE
bump ducc0 version to 0.9

### ISSUE THREAD

**Issue by mreineck** [ska-sa/codex-africanus#244]
Relevant changes:

- general:
  - Intel OneAPI compilers are now supported

- wgridder:
  - fixed a bug which could cause memory accesses beyond the end of an array

Updating to 0.9 is probably not urgent, but if you have ever noticed "weird" gridder behaviour (artifacts in the images, inexplicable crashes), they could possibly be related to the memory access bug and will hopefully be gone now.

**Comment by sjperkins** [comment]
Thanks for letting us know @mreineck!

WIll you do the honours @landmanbester?

**Comment by landmanbester** [comment]
Thanks @mreineck. I've create the PR https://github.com/ska-sa/codex-africanus/pull/245, should be in shortly. Tests are passing locally

**Comment by sjperkins** [comment]
Resolved by #245
