### ISSUE TITLE
Fix DFT computation

### ISSUE THREAD

**Issue by landmanbester** [ska-sa/codex-africanus#28]
I realise that I forgot to include the division by the direction cosine _n(l,m)_ in the implementation of the dft. Easy fix though, will submit a pull request asap

**Comment by sjperkins** [comment]
Thanks, could you also fix the missing bracket in this equation?

https://codex-africanus.readthedocs.io/en/latest/dft-api.html#africanus.dft.im_to_vis

**Comment by landmanbester** [comment]
Done. I had to modify one of the tests to account for this change, should run through now

**Comment by sjperkins** [comment]
Closed by #29
