### ISSUE TITLE
DFT tests failing

### ISSUE THREAD

**Issue by caramel-koala** [ska-sa/codex-africanus#31]
* Codex Africanus version: The latest pull from origin/master
* Python version: 3.5.2 (in the venv)
* Operating System: Linux Mint 18.2 64 bit

### Description

Ran the pytest test_dft.py, 2 of the 5 tests failed, test_vis_to_im() and test_vis_to_im_dask(). Judging from the test I ran on the tests, test_im_to_vis() passes once the /n is removed from line 64 of test_dft.py

### What I Did

```
(venv) $ pytest tests/test_dft.py
================================= test session starts ==================================
platform linux -- Python 3.5.2, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /home/antonio/Documents/Other_Git/codex-africanus, inifile: setup.cfg
collected 5 items                                                                      

tests/test_dft.py .F..F                                                          [100%]

======================================= FAILURES =======================================
____________________________________ test_vis_to_im ____________________________________

    def test_vis_to_im():
        """
        Still thinking of a better test here but the simplest test
        does exactly the same as the above. If we have an auto-correlation we expect
        to measure a flat image with value wsum
        """
        from africanus.dft.kernels import vis_to_im
        nchan = 11
    
        vis = np.ones([1, nchan], dtype=np.complex128)
        uvw = np.zeros([1, 3], dtype=np.float64)
        npix = 5
        x = np.linspace(-0.1, 0.1, npix)
        ll, mm = np.meshgrid(x, x)
        lm = np.vstack((ll.flatten(), mm.flatten())).T
        n = np.sqrt(1 - lm[:, 0]**2 - lm[:, 1]**2)
        wsum = 1.0
    
        frequency = np.linspace(1.0, 2.0, nchan, endpoint=True)
    
        image = vis_to_im(vis, uvw, lm, frequency)
    
        for i in range(nchan):
>           assert np.all(image[:, i] == wsum/n)
E           assert False
E            +  where False = <function all at 0x7fe9768cec80>(array([1., 1...., 1., 1., 1.]) == array([1.01015..., 1.01015254])
E            +    where <function all at 0x7fe9768cec80> = np.all
E               Use -v to get the full diff)

tests/test_dft.py:64: AssertionError
_________________________________ test_vis_to_im_dask __________________________________

    @pytest.mark.skipif(not have_requirements, reason="requirements not installed")
    def test_vis_to_im_dask():
        import dask.array as da
        from africanus.dft.kernels import vis_to_im as np_vis_to_im
        from africanus.dft.dask import vis_to_im as dask_vis_to_im
    
        nchan = 11
    
        vis = np.ones([100, nchan], dtype=np.complex128)
        uvw = np.zeros([100, 3], dtype=np.float64)
        npix = 5
        x = np.linspace(-0.1, 0.1, npix)
        ll, mm = np.meshgrid(x, x)
        lm = np.vstack((ll.flatten(), mm.flatten())).T
    
        frequency = np.linspace(1.0, 2.0, nchan, endpoint=True)
    
        image = np_vis_to_im(vis, uvw, lm, frequency)
    
        # set up dask arrays
        uvw_dask = da.from_array(uvw, chunks=(25, 3))
        lm_dask = da.from_array(lm, chunks=(5, 2))
        frequency_dask = da.from_array(frequency, chunks=4)
        vis_dask = da.from_array(vis, chunks=(25, 4))
    
        image_dask = dask_vis_to_im(vis_dask, uvw_dask, lm_dask, frequency_dask).compute()
    
>       assert np.allclose(image, image_dask)
E       assert False
E        +  where False = <function allclose at 0x7fe97693db70>(array([[100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],\n       [100., 100., 100., 100., 100., 100.,... 100., 100., 100., 100., 100., 100., 100.],\n       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.]]), array([[25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25.],\n       [25., 25., 25., 25., 25., 25., 25., 25., 25., 2...5., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25.],\n       [25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25.]]))
E        +    where <function allclose at 0x7fe97693db70> = np.allclose

tests/test_dft.py:157: AssertionError
========================== 2 failed, 3 passed in 2.31 seconds ==========================
```

**Comment by sjperkins** [comment]
Interesting, the unit tests passed on the last commit on master https://travis-ci.org/ska-sa/codex-africanus/jobs/394631346.

@landmanbester any thoughts?

**Comment by landmanbester** [comment]
Nope, no idea. I've just rerun the tests on my machine and they all pass
codex-africanus) landman-X3 :: ~/Projects/codex-africanus ‹master*› » pytest tests/test_dft.py
======================================================================================================================== test session starts ========================================================================================================================
platform linux2 -- Python 2.7.12, pytest-3.4.2, py-1.5.3, pluggy-0.6.0
rootdir: /home/landman/Projects/codex-africanus, inifile: setup.cfg
collected 5 items                                                                                                                                                                                                                                                   

tests/test_dft.py .....                                                                                                                                                                                                                                       [100%]

===================================================================================================================== 5 passed in 1.68 seconds ======================================================================================================================
Exception TypeError: "'NoneType' object is not callable" in <bound method ModuleRef.__del__ of <llvmlite.binding.module.ModuleRef object at 0x7fd129c3d650>> ignored

But I skip the python3.5 tests on my machine. Maybe that could have something to do with it? Also not sure where this TypeError is coming from...

**Comment by sjperkins** [comment]
@caramel-koala Try deleting your old `__pycache__` directories?

You can do this in the directory you're running things:

```
find . -name __pycache__ | xargs rm -rf
```

Although you might want to check which directories its going to nuke by taking out the `xargs rm -rf` first...

**Comment by sjperkins** [comment]
@landmanbester  I think the Exception is harmless, but it occurs on python 2.7  see https://github.com/numba/numba/issues/2818#issuecomment-372977925

**Comment by caramel-koala** [comment]
@sjperkins I tried deleting my pycache, still the fails persist, might it be the fact that I'm running 3.5.2? By my git status the only things I've changed are the addition of my pd files and their tests, everything else is the same so my thought is that it might be the environment, but since I'm running off the venv this seems unlikely as well.

**Comment by sjperkins** [comment]
Nope, tests succeed with 3.5.2 on Travis on master branch (You can check the status by hovering over and following through the green ticks/red crosses). Check out the code again and rebuild the virtual environment?

**Comment by caramel-koala** [comment]
The rebuild fixed it, all tests are now passing.
