### ISSUE TITLE
Using real phase in im_to_vis 

### ISSUE THREAD

**Issue by landmanbester** [ska-sa/codex-africanus#34]
Well, this is embarrassing. Somehow I forgot to add the factor of 1.0j to the real phase in im_to_vis. The test missed this because it only checks if im_to_vis produces the correct thing for a source at the phase centre. I will add a more thorough test with the pull request

**Comment by sjperkins** [comment]
Its a remnant of the sin/cos decomposition for purely imaginary numbers ;-)
