### ISSUE TITLE
Test for vis_to_im/R^H

### ISSUE THREAD

**Issue by caramel-koala** [ska-sa/codex-africanus#51]
* Codex Africanus version: master
* Python version: 3.6
* Operating System: Linux mint 18.2 64 bit

### Description

vis_to_im seems to be giving inconsistent answers to its matrix form, a test should be added to dft/tests check that it is consistent for future work

### What I Did
I'll be adding 2 assertion tests to check that (R^H\SigmaR)^H = R^H\SigmaR as this matrix should be hermitian and also that R^H\SigmaV is consistent with both R^H as a matrix and as the operator vis_to_im

**Comment by sjperkins** [comment]
Its probably worth checking the precision which is being used in the function with [func.inspect_llvm()](http://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html?highlight=inspect_llvm#Dispatcher.inspect_llvm)

**Comment by landmanbester** [comment]
Turns out to be a typo in something I implemented outside of africanus so false alarm, vis_to_im works fine. I've added a test to check that the image space covariance matrix (R.H Sigmainv R) is symmetric
